
'use client'
import { Download } from "lucide-react";
import { Button } from "../ui/button";
import { toast } from "sonner";
interface Prop{
    fileName:string;
    fileUrl:string;
    title:string;
    summaryText:string;
    createdAt:string;
}
export default function DownloadSummaryBtn({fileName,fileUrl,title,summaryText,createdAt}:Prop){
   const handleDownload=()=>{
    const summaryContent=`# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}

${summaryText}

Original File: ${fileName}
Generated by Doc-Summarizer....

...ThankYou for using! Made by Vivek.S.A`;
;
    const blob=new Blob([summaryContent],{type:'text/plain'});

    const url=URL.createObjectURL(blob);
    const link=document.createElement('a');
    link.href=url;
    link.download=`Summary-${title.replace(/[^a-z0-9]/gi,'_')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded Successfully.")

   }
    return <>
    <Button className="h-8 px-3 bg-rose-100 text-red-600 hover:text-amber-100 hover:scale-105 hover:bg-rose-700" 
    size={'sm'} onClick={()=>handleDownload()}>
        <Download className="h-4 w-4 mr-1"/>
        Download Summary</Button>
    </>
}